### ISSUE TITLE
ActiveLabel  activeLabel.text = ""  setText serrious performance issue on xcode 8, swift_2.3

### ISSUE THREAD

**Issue by KanybekMomukeyev** [optonaut/ActiveLabel.swift#114]
Hi, 
activeLabel.text = "" serrious performance issue on xcode 8, swift 2.3, it's seriously flickering, very poor performance. 

This was never seen before, what'is updated?

```
private func updateTextStorage(parseText parseText: Bool = true) 
```
if i add this one:

```
self.textLabel.enabledTypes = [.URL]
```
works good, but if add extra types will rise above issue.

```
self.textLabel.enabledTypes = [.URL, .Hashtag]
````

**Comment by EricHarvey** [comment]
The huge performance hit is coming from line 21 in RegexParser.swift, because it creates an NSRegularExpression on the fly every time the cell is refreshed/reloaded/etc.

I don't need the custom type for my purposes, so I stripped that out and created static NSRegularExpressions for the hashtag, mention, and URL types like so:

```
static let hashtagRegex = try! NSRegularExpression(pattern: hashtagPattern, options: [.caseInsensitive])

static let mentionRegex = try! NSRegularExpression(pattern: mentionPattern, options: [.caseInsensitive])

static let urlRegex = try! NSRegularExpression(pattern: urlPattern, options: [.caseInsensitive])
```

I also changed getElements in RegexParser to take an NSRegularExpression:

```
static func getElements(from text: String, with pattern: NSRegularExpression, range: NSRange) -> [NSTextCheckingResult]{
    return pattern.matches(in: text, options: [], range: range)
}
```

I also changed ActiveType to remove the `.custom` type, and changed `pattern` in ActiveType to return an NSRegularExpression:

```
var pattern: NSRegularExpression {
        switch self {
        case .mention: return RegexParser.mentionRegex
        case .hashtag: return RegexParser.hashtagRegex
        case .url: return RegexParser.urlRegex
    }
}
```

This solution may not work for everyone if your needs are more extensive than mine, but it should at least get you on the right path to fix the performance issue. I should also note this is for Swift 3, not 2.3, so syntax may be slightly different.

**Comment by poolqf** [comment]
Hi @KanybekMomukeyev, first of all, I would like to know with which Swift version are you having this issue. I've just updated both `master` (with Swift 3) and `swift-2.3`.

Is this happening when in a cell? The more information you give, the better.

Please try it, and tell me if it is still happening. I haven't noticed it.

Also regarding to @EricHarvey's comment, what you said is not true. ActiveLabel is not creating the regex on the fly. Also, removing `.custom` type should not change anything if you don't use it

**Comment by EricHarvey** [comment]
ActiveLabel *is* creating the` NSRegularExpression` on the fly. It didn't always, but in [this commit](https://github.com/optonaut/ActiveLabel.swift/commit/93c0f36fca2a7d19f61264830d833fedecc07581#diff-1bce8b585fe88ed52930083e384f8435) which added support for the `.custom` type, it started creating `NSRegularExpression` objects on the fly, every time a call to `RegexParser.getElements()` is made. 

This is the line:

```
guard let elementRegex = try? NSRegularExpression(pattern: pattern, options: [.CaseInsensitive]) else { return [] }
```
<br/>Prior to the aforementioned commit, the `NSRegularExpression` objects were static, so this did not affect app performance. This can be somewhat easily remedied for most cases by making the `.mention`, `.hashtag`, and `.url` `NSRegularExpression` objects static again and using those to pattern match for their respective types, but that still leaves a performance issue for the `.custom` type. Unfortunately I don't see an easy solution to that.

To answer your question, this issue will occur for both Swift 3 and 2.3 because both branches use the same line (above). And yes, it happens when in a table cell.

**Comment by poolqf** [comment]
True @EricHarvey , didn't remember about that change when I wrote the comment. Makes sense to "cache" them. I'll do it.

About the issue itself, I need more info. A demo project maybe.

**Comment by poolqf** [comment]
The "caching" has been done in https://github.com/optonaut/ActiveLabel.swift/commit/a23081d3d18e3f17f82206670d428f03acb6afd6

**Comment by EricHarvey** [comment]
Based on what I see in [`a23081d`](https://github.com/optonaut/ActiveLabel.swift/commit/a23081d3d18e3f17f82206670d428f03acb6afd6), the issue should be fixed now. The only issue was that creating an `NSRegularExpression` is pretty expensive. Doing it and using it once for a relatively static view, it wouldn't have any noticeable performance hit, but creating them over and over for use in a `UITableView`, scrolling would be noticeably choppy and the FPS would suffer. However, as an `NSRegularExpression` is now only created once per pattern, this issue should be resolved.

**Comment by poolqf** [comment]
Yep, my fault. When I did the change I completely forgot about it. Closing it. Feel free to reopen if something unexpected happens

**Comment by yoshiboarder** [comment]
Is this issues solved now? I'm also have a similar problem. I'm only enable hashtags, mentions but It has performance issues..
