### ISSUE TITLE
Setting text before setting custom enabled types doesn't work

### ISSUE THREAD

**Issue by retendo** [optonaut/ActiveLabel.swift#133]
On the swift-2.3 branch:

It seems that this is just an issue for custom types:

```
label.enabledTypes = [customType]
label.customColor[customType] = someColor
label.text = someText
```
works.

```
label.text = someText
label.enabledTypes = [customType]
label.customColor[customType] = someColor
```
doesn't.

In contrast with the hashtag type:

```
label.text = someText
label.enabledTypes = [.Hashtag]
label.hashtagColor = someColor
```
works.

**Comment by retendo** [comment]
Nothing too bad, but if it is not documented, it can give you some headache for half an hour. ;)

**Comment by poolqf** [comment]
Well, it is not that it works with `.hashtag` and not with other types, it is that by default, `enabledTypes` contains `.mention`, `.hashtag` & `.url`. So setting the text, since it is enabled, works.

I kind of makes sense that the types that are going to be highlighted are the ones that are set the moment you set the text, no? 🤔

Even though, I'll think in the best way to document it

**Comment by henryeverett** [comment]
It would be great if it worked whenever the text is set. This is particularly useful if the text is already set in Interface Builder. That way it doesn't have to be duplicated in code.

**Comment by maxmzd** [comment]
This had me guessing until I found this. Please add it to the docs for new users.
