### ISSUE TITLE
Mention and hashtag regex values should be exposed as properties

### ISSUE THREAD

**Issue by diegoperini** [optonaut/ActiveLabel.swift#157]
Right now we need to unlock the pod to be able to edit.

**Comment by diegoperini** [comment]
I hope this won't be closed.

**Comment by maziyarpanahi** [comment]
Hi @diegoperini, you can always reopen a closed issue or open a new one. The bot detects `stale` issues which haven't had any activity for the past 6 months. This means the issue or request won't be solved or developed by the maintainers. Unfortunately, whether it is open or closed won't change that result.
PS: why do you need to change the regex for mention and hashtag when you can have your own `custom types`?  https://github.com/optonaut/ActiveLabel.swift#custom-types

**Comment by diegoperini** [comment]
Because semantically my custom regex rules stil capture mentions and
hashtags but with additional improvements for Turkish language. Writing
custom types felt overkill and redundant.

**Comment by maziyarpanahi** [comment]
I understand, but that is why we have `custom types` since there is no right regex pattern for all the use cases. 
Now I understand the issue clearly, this won't be fixed since we have custom types so you can turn off the .mention .url .hashtag if you don't need them and move on with your improved custom types which could share some similarities.
Custome types are the best practice and flexible when it comes to these types of situations.
Feel free to open a new issue if you have any question in custom types.

Best,
