### ISSUE TITLE
IB Designables: Failed to render and update auto layout status

### ISSUE THREAD

**Issue by alexanderkhitev** [optonaut/ActiveLabel.swift#254]
Hello! I use ActiveLabel in IB and I get this error 
```
 IB Designables: Failed to render and update auto layout status for RegisterMainViewController (Ovd-Ud-K0B): dlopen(ActiveLabel.framework, 1): no suitable image found.  Did find:
	ActiveLabel.framework: required code signature missing for 'ActiveLabel.framework'
```

**Comment by yunnnyunnn** [comment]
+1. Different message tho.
Xcode 9.3 (9E145)
Never happened before Xcode update.
```
IB Designables: Failed to render and update auto layout status for View: Symbol not found: __T0SS13CharacterViewVN
  Referenced from: ActiveLabel.framework
  Expected in: /../usr/lib/swift/iphonesimulator/libswiftCore.dylib
 in ActiveLabel.framework
```

**Comment by alexanderkhitev** [comment]
I solved this problem as follows, I made a class that inherits from ActiveLabel and used this new class in Storyboard. Of course, it's better to solve this problem on the framework level.

**Comment by maziyarpanahi** [comment]
Hi,

This is an issue with new Xcode and new Pod 1.5 and it's been covered here:
https://github.com/CocoaPods/CocoaPods/issues/7606

Either downgrade your CocoaPods to 1.4 or use the workaround that is mentioned here: (I used this workaround for myself and it worked)
https://github.com/CocoaPods/CocoaPods/issues/7606#issuecomment-381279098

Although this issue is not related to this library, I leave it open for the time being as it will hit most of the users.

**Comment by s2339956** [comment]
I'm facing the same issue.

**Comment by maziyarpanahi** [comment]
I already posted the solution and it's not related to this library.

**Comment by akashhipl** [comment]
I'm facing the same issue.

**Comment by maziyarpanahi** [comment]
Please follow the instructions: https://github.com/CocoaPods/CocoaPods/issues/7606#issuecomment-381279098

**Comment by muqbilk** [comment]
I would suggest trying this first 
`pod deintegrate`

then re-install , you can choose whatever version you are comfortable with :
 `pod _1.5.3_ install`

Then rebuild and see, It worked for me !

**Comment by CodeKunal** [comment]
Restating Xcode worked for me.
